#format = '$username$hostname$time$directory$sudo$git_status$line_break$character'
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$time\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$shell\
$character"""

[username]
format = "[$user]($style) :: "
show_always = true
style_root = "bold red"
style_user = "bold blue"

[hostname]
disabled = false
format = "[$ssh_symbol$hostname]($style) :: "
ssh_only = false
style = "bold dimmed green"
#trim_at = "-"

[time]
disabled = false
format = "[$time]($style) :: "
style = "bold bright-black"
#time_format = "%T"

[directory]
style = "yellow"
truncate_to_repo = true
truncation_length = 0
truncation_symbol = "repo: "

#[sudo]
#disabled = false

#[git_status]
#ahead = "⇡${count}"
#behind = "⇣${count}"
#deleted = "x"
#diverged = "⇕⇡${ahead_count}⇣${behind_count}"
#style = "white"

# Last param in the first line/row
#[cmd_duration]
#disabled = false
#format = "took [$duration]($style)"
#min_time = 1


#[character]
#error_symbol = " [×](bold red)"
#success_symbol = " >(bold red)"

# SYMBOLS
[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
